import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="bg-body text-white">
                <Header />
                {children}
                <Footer />
                <div id="modal-root-content"/>
            </body>
        </html>
    );
}
